mj:
  db:
    host: 192.168.100.128 # 修改虚拟机IP地址
    port: 3306
    database: mj_media
    un: root
    pw: 123456 # 修改为docker中的MySQL密码
  redis:
    host: 192.168.100.128 # 修改虚拟机IP地址
    port: 6379
    password: 123456
    database: 0
  media:
    ffmpeg-path: D:\software\ffmpeg\ffmpeg-2026-06-04-git-c27a3b12e3-essentials_build\bin\ffmpeg.exe
    work-dir: D:\software\ffmpeg\manju-media